

hikari:
  config:
    idletimeout: ${HIKARI_IDLETIMEOUT}
    maximumpoolsize: ${HIKARI_MAXIMUMPOOLSIZE}
    dsclassname: ${HIKARI_DSCLASSNAME}
    poolname: ${HIKARI_POOLNAME}
    testquery: ${HIKARI_TESTQUERY}
  ds:
    url: ${HIKARI_DS_URL}
    usr: ${HIKARI_DS_USR}
    psw: ${HIKARI_DS_PSW}


sql:
  cliente:
    
    create:
      insert into dbcadclidev.cliente(
      cliente_name,
      cliente_surname,
      cliente_age,
      cliente_address,
      cliente_city,
      cliente_country,
      cliente_mobile,
      cliente_email)
      values(?,?,?,?,?,?,?,?)
      
    update:
      update dbcadclidev.cliente set
      cliente_name = ?,
      cliente_surname = ?,
      cliente_age = ?,
      cliente_address = ?,
      cliente_city = ?,
      cliente_country = ?,
      cliente_mobile = ?,
      cliente_email = ?
      where cliente_id = ?
      
    findpage:
      select
      cliente_id,
      cliente_name,
      cliente_surname,
      cliente_age,
      cliente_address,
      cliente_city,
      cliente_country,
      cliente_mobile,
      cliente_email
      from dbcadclidev.cliente
      _orderBy_
      limit ?, ?
      
    search:
      select cliente_id _select_
      from dbcadclidev.cliente
      _where_
      _orderBy_

